import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"贡献指南","description":"","frontmatter":{},"headers":[],"relativePath":"zh/dev/CONTRIBUTING.md","filePath":"zh/dev/CONTRIBUTING.md","lastUpdated":1783687813000}');
const _sfc_main = { name: "zh/dev/CONTRIBUTING.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="贡献指南" tabindex="-1">贡献指南 <a class="header-anchor" href="#贡献指南" aria-label="Permalink to &quot;贡献指南&quot;">​</a></h1><p>感谢你对 Sea Lantern 项目的关注！这份文档将帮助你了解如何为项目做出贡献。</p><h2 id="可接受-pr-范围" tabindex="-1">可接受 PR 范围 <a class="header-anchor" href="#可接受-pr-范围" aria-label="Permalink to &quot;可接受 PR 范围&quot;">​</a></h2><p>对于非项目组织成员，当前优先接受范围清楚、审查成本可控的 PR：</p><ul><li>文档修正</li><li>i18n 文案修正</li><li>明确且小范围的错别字、链接或描述修复</li><li>高质量、可复现、非 AI 批量生成的 bug fix</li><li>已在 Issue 中讨论，并被项目组采纳的功能、重构或行为调整</li></ul><div class="warning custom-block"><p class="custom-block-title">注意</p><p>较大的功能、架构、交互或目录结构改动，请先提交 Issue 讨论。未经过讨论且成本较高的 PR，项目组可能会直接关闭。</p></div><h3 id="为什么" tabindex="-1">为什么？ <a class="header-anchor" href="#为什么" aria-label="Permalink to &quot;为什么？&quot;">​</a></h3><p>这样做是为了保证贡献范围可控，避免贡献方向与开发组计划冲突，同时给高质量修复和已采纳提案留出空间。</p><p>我们的原则是：<strong>任何贡献对项目的价值都应大于审查它所需的工作量</strong>。</p><p>开始较大改动前，请先与项目组沟通。</p><p>开发组邀请会综合考虑：</p><ul><li>工程判断和代码质量；</li><li>对项目结构、边界和维护成本的理解；</li><li>过往项目经验和问题定位能力；</li><li>沟通、协作和长期维护意愿；</li><li>持续贡献的稳定性和可靠性。</li></ul><h2 id="开发环境要求" tabindex="-1">开发环境要求 <a class="header-anchor" href="#开发环境要求" aria-label="Permalink to &quot;开发环境要求&quot;">​</a></h2><table tabindex="0"><thead><tr><th>依赖</th><th>版本</th></tr></thead><tbody><tr><td>Node.js</td><td>24 LTS（最低 20.19.0）</td></tr><tr><td>Rust</td><td>stable</td></tr><tr><td>pnpm</td><td>9.15.9</td></tr></tbody></table><h2 id="代码规范" tabindex="-1">代码规范 <a class="header-anchor" href="#代码规范" aria-label="Permalink to &quot;代码规范&quot;">​</a></h2><h3 id="rust-代码规范" tabindex="-1">Rust 代码规范 <a class="header-anchor" href="#rust-代码规范" aria-label="Permalink to &quot;Rust 代码规范&quot;">​</a></h3><ol><li><p><strong>格式化</strong></p><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># 提交前最好运行</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">cargo</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> fmt</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --all</span></span></code></pre></div></li><li><p><strong>代码检查</strong></p><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># 建议通过所有 clippy 检查</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">cargo</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> clippy</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --all-targets</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --workspace</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> -D</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> warnings</span></span></code></pre></div></li><li><p><strong>命名规范</strong></p><ul><li>文件名：使用 <code>snake_case</code>（如 <code>server_manager.rs</code>）</li><li>函数名：使用 <code>snake_case</code>（如 <code>get_server_list</code>）</li><li>结构体：使用 <code>PascalCase</code>（如 <code>ServerInstance</code>）</li><li>常量：使用 <code>SCREAMING_SNAKE_CASE</code>（如 <code>MAX_MEMORY</code>）</li></ul></li><li><p><strong>注释规范</strong></p><ul><li>公共 API 建议留有文档注释（<code>///</code>）</li><li>复杂逻辑建议添加行内注释（<code>//</code>）</li><li>避免无意义的注释</li><li>避免出现 <code>Fuck the fmt</code> 类似的语句</li></ul></li><li><p><strong>错误处理</strong></p><ul><li>使用 <code>Result&lt;T, String&gt;</code> 返回错误</li><li>错误信息要清晰、用户友好</li><li>避免使用 <code>unwrap()</code>，优先使用 <code>?</code> 或 <code>unwrap_or</code></li></ul></li></ol><h3 id="前端代码规范" tabindex="-1">前端代码规范 <a class="header-anchor" href="#前端代码规范" aria-label="Permalink to &quot;前端代码规范&quot;">​</a></h3><ol><li><p><strong>Vue 组件</strong></p><ul><li>组件名使用 <code>PascalCase</code>（如 <code>ServerCard.vue</code>）</li><li>使用 <code>&lt;script setup&gt;</code> 语法</li><li>Props 和 emits 必须定义类型</li></ul></li><li><p><strong>TypeScript</strong></p><ul><li>启用严格模式</li><li>避免使用 <code>any</code>，优先使用具体类型</li><li>接口名使用 <code>PascalCase</code></li></ul></li><li><p><strong>样式</strong></p><ul><li>使用 CSS 变量（<code>var(--sl-*)</code>）</li><li>避免硬编码颜色值</li><li>使用 scoped 样式</li></ul></li><li><p><strong>格式化和检查</strong></p><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># 格式化代码</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">pnpm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> fmt</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># 检查格式</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">pnpm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> fmt:check</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># Lint 检查</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">pnpm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> lint</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># 自动修复 Lint 问题</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">pnpm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> lint:fix</span></span></code></pre></div></li><li><p><strong>变量引用检查</strong></p><ul><li>声明变量时指定明确类型</li><li>避免使用 <code>any</code>，使用具体类型</li><li>使用 <code>ref&lt;T&gt;</code> 或 <code>reactive</code> 时指定泛型类型</li></ul></li></ol><h3 id="ui-组件与图标" tabindex="-1">UI 组件与图标 <a class="header-anchor" href="#ui-组件与图标" aria-label="Permalink to &quot;UI 组件与图标&quot;">​</a></h3><ul><li><p><strong>优先使用 Headless UI（Vue v1）与按需导入的图标库（如 Lucide）</strong>：</p><ul><li>Headless UI（<a href="https://headlessui.com/v1/vue%EF%BC%89%E6%8F%90%E4%BE%9B%E6%97%A0%E6%A0%B7%E5%BC%8F%E3%80%81%E5%8F%AF%E8%AE%BF%E9%97%AE%E6%80%A7%E7%9A%84%E4%BA%A4%E4%BA%92%E7%BB%84%E4%BB%B6%EF%BC%88%E5%A6%82" target="_blank" rel="noreferrer">https://headlessui.com/v1/vue）提供无样式、可访问性的交互组件（如</a> <code>Listbox</code>、<code>Disclosure</code>、<code>Dialog</code>），推荐在需要复杂交互（弹出、折叠、可访问键盘支持）时优先复用它们，以减少手写 DOM 与键盘/ARIA 处理。</li><li>图标使用可按需导入的组件库（如 Lucide：<a href="https://lucide.dev/icons/" target="_blank" rel="noreferrer">https://lucide.dev/icons/</a> 或示例图标 <a href="https://lucide.dev/icons/paint-roller?search=Palette%EF%BC%89%EF%BC%8C%E4%B8%8D%E8%A6%81%E5%9C%A8%E9%A1%B9%E7%9B%AE%E4%B8%AD%E5%A4%A7%E9%87%8F%E7%A1%AC%E7%BC%96%E7%A0%81" target="_blank" rel="noreferrer">https://lucide.dev/icons/paint-roller?search=Palette），不要在项目中大量硬编码</a> <code>&lt;svg&gt;</code> 路径或重复 DOM。按需导入能保持包体积小并提高可维护性。</li><li>推荐实践：使用 Headless UI 的 <code>Listbox</code> 替换自定义下拉/选择器；使用 Lucide 的图标组件（如 <code>Palette</code> / <code>Paint-roller</code>）替换硬编码图标。</li></ul><p>这样可减少冗余 DOM、统一可访问性处理，并把样式与行为分离，便于维护。</p></li></ul><h2 id="git-工作流" tabindex="-1">Git 工作流 <a class="header-anchor" href="#git-工作流" aria-label="Permalink to &quot;Git 工作流&quot;">​</a></h2><h3 id="分支命名" tabindex="-1">分支命名 <a class="header-anchor" href="#分支命名" aria-label="Permalink to &quot;分支命名&quot;">​</a></h3><ul><li><code>feat/功能名</code> - 新功能</li><li><code>fix/问题描述</code> - Bug 修复</li><li><code>refactor/任务描述</code> - 重构</li><li><code>chore/任务描述</code> - 杂项任务</li><li><code>docs/文档说明</code> - 文档更新</li></ul><h3 id="commit-建议" tabindex="-1">Commit 建议 <a class="header-anchor" href="#commit-建议" aria-label="Permalink to &quot;Commit 建议&quot;">​</a></h3><p>提交前，Husky 会通过 lint-staged 格式化已暂存的前端和文档文件。提交信息仍建议保持清晰、可读，方便后续审查与回溯。</p><p>推荐使用简洁的约定式风格，例如：</p><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>feat(scope): 新增某项能力</span></span>
<span class="line"><span>fix: 修复某个具体问题</span></span>
<span class="line"><span>chore: 调整构建或目录结构</span></span></code></pre></div><p>提交前建议自行运行必要检查，CI 会在 PR/推送时继续校验代码质量。</p><h3 id="pull-request-流程" tabindex="-1">Pull Request 流程 <a class="header-anchor" href="#pull-request-流程" aria-label="Permalink to &quot;Pull Request 流程&quot;">​</a></h3><ol><li><p><strong>Fork 项目并创建分支</strong></p><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">git</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> checkout</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> -b</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> feat/your-feature</span></span></code></pre></div></li><li><p><strong>开发并提交</strong></p><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># 确保代码通过检查</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">cargo</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> fmt</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --all</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --check</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">cargo</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> check</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --all-targets</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --workspace</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">cargo</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> clippy</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --all-targets</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --workspace</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> -D</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> warnings</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">pnpm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> fmt:check</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">pnpm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> lint</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">pnpm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> build:check</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># 提交变更</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">git</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> add</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> .</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">git</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> commit</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> -m</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> &quot;feat(scope): 你的功能描述&quot;</span></span></code></pre></div></li><li><p><strong>推送并创建 PR</strong></p><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">git</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> push</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> origin</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> feat/your-feature</span></span></code></pre></div></li><li><p><strong>PR 标题和描述</strong></p><ul><li>标题简洁明了（不超过 70 字符）</li><li>描述包含： <ul><li>变更摘要</li><li>测试方法</li><li>相关 Issue（如有）</li></ul></li></ul></li></ol><h2 id="代码审查标准" tabindex="-1">代码审查标准 <a class="header-anchor" href="#代码审查标准" aria-label="Permalink to &quot;代码审查标准&quot;">​</a></h2><h3 id="建议满足" tabindex="-1">建议满足 <a class="header-anchor" href="#建议满足" aria-label="Permalink to &quot;建议满足&quot;">​</a></h3><ul><li>✅ 通过所有 CI 检查</li><li>✅ 代码格式正确（cargo fmt / oxfmt）</li><li>✅ 无 clippy 警告</li><li>✅ 无 oxlint 警告</li><li>✅ 功能完整且可用</li><li>✅ 无明显的性能问题</li></ul><h3 id="推荐满足" tabindex="-1">推荐满足 <a class="header-anchor" href="#推荐满足" aria-label="Permalink to &quot;推荐满足&quot;">​</a></h3><ul><li>有适当的注释</li><li>有相关测试（如适用）</li><li>更新了相关文档</li><li>UI 变更符合设计规范</li></ul><h2 id="常见问题" tabindex="-1">常见问题 <a class="header-anchor" href="#常见问题" aria-label="Permalink to &quot;常见问题&quot;">​</a></h2><h3 id="如何运行开发环境" tabindex="-1">如何运行开发环境？ <a class="header-anchor" href="#如何运行开发环境" aria-label="Permalink to &quot;如何运行开发环境？&quot;">​</a></h3><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">pnpm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> install</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">pnpm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> tauri</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> dev</span></span></code></pre></div><h3 id="如何构建发布版本" tabindex="-1">如何构建发布版本？ <a class="header-anchor" href="#如何构建发布版本" aria-label="Permalink to &quot;如何构建发布版本？&quot;">​</a></h3><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">pnpm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> tauri</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> build</span></span></code></pre></div><p>但我们不推荐本地构建用来发布到 Release 中</p><p>如果你要按仓库当前的 GitHub Actions 流程发布正式版本或 Nightly 版本，请以仓库中的工作流配置为准。</p><h3 id="clippy-检查失败怎么办" tabindex="-1">Clippy 检查失败怎么办？ <a class="header-anchor" href="#clippy-检查失败怎么办" aria-label="Permalink to &quot;Clippy 检查失败怎么办？&quot;">​</a></h3><ol><li>查看具体警告信息</li><li>运行 <code>cargo clippy --fix</code> 自动修复（部分问题）</li><li>手动修复剩余问题</li><li>如果某些警告不合理，可以使用 <code>#[allow(clippy::...)]</code> 标记</li></ol><h3 id="格式化检查失败怎么办" tabindex="-1">格式化检查失败怎么办？ <a class="header-anchor" href="#格式化检查失败怎么办" aria-label="Permalink to &quot;格式化检查失败怎么办？&quot;">​</a></h3><p>尝试:</p><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">cargo</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> fmt</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --all</span></span></code></pre></div><h2 id="获取帮助" tabindex="-1">获取帮助 <a class="header-anchor" href="#获取帮助" aria-label="Permalink to &quot;获取帮助&quot;">​</a></h2><ul><li>在 Issue 中提问</li><li>联系维护者</li><li>查看项目文档</li></ul><h2 id="行为准则" tabindex="-1">行为准则 <a class="header-anchor" href="#行为准则" aria-label="Permalink to &quot;行为准则&quot;">​</a></h2><ul><li>尊重所有贡献者</li><li>保持友好和专业</li><li>接受建设性的反馈</li><li>帮助新手贡献者</li></ul><hr><p>再次感谢你的贡献！</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("zh/dev/CONTRIBUTING.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const CONTRIBUTING = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  CONTRIBUTING as default
};
